---
- name: Check Debian updates and pending reboot status
  hosts: "{{ target_hosts }}"
  become: true
  tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes

    - name: List available updates
      ansible.builtin.shell: apt list --upgradable
      register: update_result
      changed_when: false

    - name: Display available updates
      ansible.builtin.debug:
        var: update_result.stdout_lines

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Display reboot status
      ansible.builtin.debug:
        msg: "Reboot required: {{ reboot_required.stat.exists }}"
