---
- name: Upgrade OPNsense Firewall
  hosts: "{{ target_hosts }}"
  become: yes
  tasks:
    - name: Check for available updates
      ansible.builtin.command:
        cmd: opnsense-update -M
      register: update_check
      changed_when: false

    - name: Display available updates
      ansible.builtin.debug:
        msg: "{{ update_check.stdout }}"

