---
- name: Run updates on linux servers
  hosts: "{{ target_hosts }}"
  become: yes
  become_user: root
  tasks:
    - name: Update package lists (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Upgrade all packages (Debian/Ubuntu)
      ansible.builtin.apt:
        upgrade: dist
      when: ansible_facts['os_family'] == "Debian"

    - name: Check if reboot is required (Debian/Ubuntu)
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required
      when: ansible_facts['os_family'] == "Debian"

    - name: Reboot the server if required (Debian/Ubuntu)
      ansible.builtin.reboot:
      when: reboot_required.stat.exists
